name: Tests Code Coverage

on: [pull_request]

jobs:
  phpunit-code-coverage:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Setup environment
        run: cp -r env/codecov/. .

      - name: Update composer
        run: composer update

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit  --coverage-clover coverage.xml

      - name: Code Coverage upload
        uses: codecov/codecov-action@v1
