name: Tests Code Coverage

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  phpunit-code-coverage:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        run: apt-get install git -y

      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Setup environment
        run: cp -r env/codecov/. .

      - name: Update composer
        run: composer update

      - name: require topic-types
        run: COMPOSER_ROOT_VERSION=0.9.9 composer require escolalms/topic-types

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: XDEBUG_MODE=coverage vendor/bin/phpunit  --coverage-clover coverage.xml

      - name: codecov upload
        uses: codecov/codecov-action@v1

      - name: Setup Code Climate test-reporter
        run: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - name: Convert
        run: ./cc-test-reporter format-coverage coverage.xml -t clover -o codeclimate.0.json

      - name: Upload
        run: ./cc-test-reporter upload-coverage -i codeclimate.0.json
        env:
          CC_TEST_REPORTER_ID: 8539f41f60574ac436ad0be5c4a05633ca02b4614ecbcf0acd9dd76ef4130d80
